### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MiniGod** [koddsson/LGTM#9]
It doesn't seem to do anything.
The service worker caches all the images when opening on [https](https://koddsson.github.io/LGTM/), but that's about it...
\#bestbugreportever #lgtminsucks

**Comment by koddsson** [comment]
Yeah. I haven't been updating this at all and can be considered #abandonded

**Comment by MiniGod** [comment]
![Nooo!](https://i.giphy.com/MBz2IwLB4fmnK.gif)

**Comment by MiniGod** [comment]
@koddsson FYI: Using this now: [https://gif.now.sh/lgtm.gif](https://gif.now.sh/lgtm.gif)
It proxies from giphy, but they look alright...

Also, it's different every time, so might be dangerous. However, github caches these images in their CDN, so you won't always see different images.

![LGTM](https://gif.now.sh/lgtm.gif)

**Comment by MiniGod** [comment]
Hold on! How long does GitHub cache that image? Will [https://gif.now.sh/lgtm.gif](https://gif.now.sh/lgtm.gif) show Rocky forever??

**Comment by koddsson** [comment]
Nice! It seems that going to https://gif.now.sh/lgtm will give you a random URL that will always go to the same GIF so that's handy. You could cycle through https://gif.now.sh/lgtm until it gives you one you want and then use the direct link to that one :)
